language: java
dist: xenial
jdk:
    - openjdk11
    - openjdk10
    - openjdk8
services:
    - xvfb
    - mysql

cache:
    directories:
        - "$HOME/.m2"
before_install:
    - rmiregistry -J-Djava.rmi.server.useCodebaseOnly=false &
    - mysql -u root -e "create database bspq19-s4";
    - mysql -u root -e "CREATE USER 'spq'@'%' IDENTIFIED BY 'spq'";
    - mysql -u root -e "GRANT ALL ON bspq19-s4.* TO 'spq'@'%'";